[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -jar target/familia_plus-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx1024m"
JAVA_OPTS = "-Xmx512m -Xms256m"